# Generated by Django 3.0.6 on 2020-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
