# Generated by Django 3.0.6 on 2020-06-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_contestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestevent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
