# Generated by Django 3.0.6 on 2020-06-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_puser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puser',
            options={'verbose_name': 'Planner 사용자', 'verbose_name_plural': 'Planner 사용자'},
        ),
        migrations.AddField(
            model_name='puser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
