# Generated by Django 3.0.6 on 2020-06-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20200607_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puser',
        ),
    ]
